version: '3'

services:
  server:
    restart: always
    #the below name is how this container will be referenced by docker
    container_name: rust_server
    image: didstopia/rust-server:latest
    #a bind mound is ALWAYS recommended if you are self-hosting in your home. If you are using something like DigitalOcean or Linode a Volume may be better
    volumes:
    - /pathto/bindmount/:/steamcmd/rust
    environment: 
    #You can define this for accurate logging. Completely optional
    - TZ=America/Chicago
    #this is the name that is displayed on Rust, Steam, and Scraper server browsers
    - RUST_SERVER_NAME=coolserver
    #A short blurb about your server
    - RUST_SERVER_DESCRIPTION=the best rust server ever
    #how often the game state saves in seconds. The below value is 15 minutes
    - RUST_SERVER_SAVE_INTERVAL=900
    #Enables/Disables the Web Interface for RCON. Be sure to set RUST_RCON_PASSWORD
    - RUST_RCON_WEB=0
    - RUST_RCON_PASSWORD = mysupersecurepassword
    #Updates on container start if set to 1
    - RUST_UPDATE_CHECKING=1
    - RUST_SERVER_MAXPLAYERS=15
    - RUST_SERVER_URL=https://dognet.fun
    #if server is unresponsive, shutdown
    - RUST_HEARTBEAT=1
    ports:
    #make sure these are allowed on your firewall as well.
    #Game ports
    - 28015:28015
    - 28015:28015/udp
    #RCON Port. Be sure you have set RUST_RCON_PASSWORD
    - 28016:28016
    #RUST+ Port. The app lets you remote detonate explosives, watch cameras and more. Super cool!
    - 28082:28082
